version: 2
env:
  - CGO_ENABLED=0
  - PROJECT=github.com/cloudradar-monitoring/cagent
  - LICENSE_PROPRIETARY=released under a proprietary license. See license.txt
builds:
  - id: cagent
    main: ./cmd/cagent
    binary: cagent
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "5"
      - "6"
      - "7"
    # List of combinations of GOOS + GOARCH + GOARM to ignore.
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm64
    ldflags:
      - '-s -w -X {{.Env.PROJECT}}.Version={{.Version}} -X "{{.Env.PROJECT}}.SelfUpdatesFeedURL={{.Env.SELF_UPDATES_FEED_URL}}"'
  - id: csender
    main: ./cmd/csender
    binary: csender
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    # List of combinations of GOOS + GOARCH + GOARM to ignore.
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm64
    ldflags:
      - "-s -w -X {{.Env.PROJECT}}.Version={{.Version}}"
  - id: jobmon
    main: ./cmd/jobmon
    binary: jobmon
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    # List of combinations of GOOS + GOARCH + GOARM to ignore.
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm64
    ldflags:
      - "-s -w -X {{.Env.PROJECT}}.Version={{.Version}}"
  - id: cagent_proprietary
    main: ./cmd/cagent
    binary: cagent
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - '-s -w -X {{.Env.PROJECT}}.Version={{.Version}} -X "{{.Env.PROJECT}}.LicenseInfo={{.Env.LICENSE_PROPRIETARY}}" -X "{{.Env.PROJECT}}.SelfUpdatesFeedURL={{.Env.PROPRIETARY_SELF_UPDATES_FEED_URL}}"'
  - id: csender_proprietary
    main: ./cmd/csender
    binary: csender
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - '-s -w -X {{.Env.PROJECT}}.Version={{.Version}} -X "{{.Env.PROJECT}}.LicenseInfo={{.Env.LICENSE_PROPRIETARY}}"'
  - id: jobmon_proprietary
    main: ./cmd/jobmon
    binary: jobmon
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - '-s -w -X {{.Env.PROJECT}}.Version={{.Version}} -X "{{.Env.PROJECT}}.LicenseInfo={{.Env.LICENSE_PROPRIETARY}}"'
archives:
  - id: cagent
    builds:
      - cagent
      - csender
      - jobmon
    files:
      - README.md
      - example.config.toml
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    maintainer: CloudRadar GmbH <ops@cloudradar.io>

    vendor: cloudradar GmbH
    homepage: https://cloudradar.io
    description: Monitoring agent to report CPU, disk, mem and net metrics
    license: MIT

    # Formats to be generated.
    formats:
      - deb
      - rpm

    dependencies:
      - sudo

    recommends:
      - dmidecode
      - usbutils
      - ca-certificates
      - dbus

    # Override default /usr/local/bin destination for binaries
    bindir: /usr/bin

    contents:
      # Empty folders that should be created and managed by the packager implementation.
      - dst: /var/log/cagent
        type: dir
      - dst: /var/lib/cagent/jobmon
        type: dir
      - dst: /etc/cagent
        type: dir

      - src: example.config.toml
        dst: /etc/cagent/example.config.toml
      - src: cacert.pem
        dst: /etc/cagent/cacert.pem
      - src: pkg-scripts/cagent-dmidecode
        dst: /etc/sudoers.d/cagent-dmidecode
      - src: pkg-scripts/cagent-docker
        dst: /etc/sudoers.d/cagent-docker
      - src: pkg-scripts/cagent-smartctl
        dst: /etc/sudoers.d/cagent-smartctl

    scripts:
      preinstall: "pkg-scripts/preinstall.sh"
      postinstall: "pkg-scripts/postinstall.sh"
      preremove: "pkg-scripts/preremove.sh"

    overrides:
      deb:
        contents:
          - src: pkg-scripts/cagent-apt-get
            dst: /etc/sudoers.d/cagent-apt-get
      rpm:
        contents:
          - src: pkg-scripts/cagent-yum
            dst: /etc/sudoers.d/cagent-yum
          - src: pkg-scripts/cagent-dnf
            dst: /etc/sudoers.d/cagent-dnf
        scripts:
          postinstall: "pkg-scripts/postinstall-rpm.sh"
          preremove: "pkg-scripts/preremove-rpm.sh"

release:
  github:
    owner: cloudradar-monitoring
    name: cagent
  draft: true
