env:
  - CGO_ENABLED=0
  - PROJECT=github.com/cloudradar-monitoring/cagent
  - LICENSE_PROPRIETARY=released under a proprietary license. See license.txt
builds:
- id: cagent
  main: ./cmd/cagent
  binary: cagent
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7
  # List of combinations of GOOS + GOARCH + GOARM to ignore.
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: arm
    - goos: darwin
      goarch: arm
    - goos: windows
      goarch: arm64
    - goos: darwin
      goarch: arm64
  ldflags:
    - "-s -w -X {{.Env.PROJECT}}.Version={{.Version}}"
- id: csender
  main: ./cmd/csender
  binary: csender
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7
  # List of combinations of GOOS + GOARCH + GOARM to ignore.
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: arm
    - goos: darwin
      goarch: arm
    - goos: windows
      goarch: arm64
    - goos: darwin
      goarch: arm64
  ldflags:
    - "-s -w -X {{.Env.PROJECT}}.Version={{.Version}}"
- id: jobmon
  main: ./cmd/jobmon
  binary: jobmon
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7
  # List of combinations of GOOS + GOARCH + GOARM to ignore.
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: arm
    - goos: darwin
      goarch: arm
    - goos: windows
      goarch: arm64
    - goos: darwin
      goarch: arm64
  ldflags:
    - "-s -w -X {{.Env.PROJECT}}.Version={{.Version}}"
- id: cagent_proprietary
  main: ./cmd/cagent
  binary: cagent
  goos:
    - windows
  goarch:
    - 386
    - amd64
  ldflags:
    - "-s -w -X {{.Env.PROJECT}}.Version={{.Version}} -X \"{{.Env.PROJECT}}.LicenseInfo={{.Env.LICENSE_PROPRIETARY}}\""
- id: csender_proprietary
  main: ./cmd/csender
  binary: csender
  goos:
    - windows
  goarch:
    - 386
    - amd64
  ldflags:
    - "-s -w -X {{.Env.PROJECT}}.Version={{.Version}} -X \"{{.Env.PROJECT}}.LicenseInfo={{.Env.LICENSE_PROPRIETARY}}\""
- id: jobmon_proprietary
  main: ./cmd/jobmon
  binary: jobmon
  goos:
    - windows
  goarch:
    - 386
    - amd64
  ldflags:
    - "-s -w -X {{.Env.PROJECT}}.Version={{.Version}} -X \"{{.Env.PROJECT}}.LicenseInfo={{.Env.LICENSE_PROPRIETARY}}\""
archives:
  - id: cagent
    builds:
      - cagent
      - csender
      - jobmon
    files:
      - README.md
      - example.config.toml
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  maintainer: CloudRadar GmbH <ops@cloudradar.io>

  vendor: cloudradar GmbH
  homepage: https://cloudradar.io
  description: Monitoring agent to report CPU, disk, mem and net metrics
  license: MIT

  # Formats to be generated.
  formats:
    - deb
    - rpm

  dependencies:
    - sudo

  recommends:
    - dmidecode
    - usbutils
    - ca-certificates
    - dbus

  # Override default /usr/local/bin destination for binaries
  bindir: /usr/bin

  # Empty folders that should be created and managed by the packager implementation.
  empty_folders:
    - /var/log/cagent
    - /var/lib/cagent/jobmon
    - /etc/cagent

  files:
    "example.config.toml": "/etc/cagent/example.config.toml"
    "cacert.pem": "/etc/cagent/cacert.pem"
    "pkg-scripts/cagent-dmidecode": "/etc/sudoers.d/cagent-dmidecode"
    "pkg-scripts/cagent-docker": "/etc/sudoers.d/cagent-docker"
    "pkg-scripts/cagent-smartctl": "/etc/sudoers.d/cagent-smartctl"

  scripts:
    preinstall: "pkg-scripts/preinstall.sh"
    postinstall: "pkg-scripts/postinstall.sh"
    preremove: "pkg-scripts/preremove.sh"

  overrides:
    deb:
      files:
        "pkg-scripts/cagent-apt-get": "/etc/sudoers.d/cagent-apt-get"
    rpm:
      files:
        "pkg-scripts/cagent-yum": "/etc/sudoers.d/cagent-yum"
        "pkg-scripts/cagent-dnf": "/etc/sudoers.d/cagent-dnf"
      scripts:
        postinstall: "pkg-scripts/postinstall-rpm.sh"
        preremove: "pkg-scripts/preremove-rpm.sh"

release:
  github:
    owner: cloudradar-monitoring
    name: cagent
  draft: true
